// Generated by the Playwright Test Script Generator agent.
// Exploration URL: https://www.saucedemo.com/

import { test, expect } from '@playwright/test';
import { SwagLabsApp } from '../src/pages/swag-labs.app.js';

test('4 - Checkout happy path', async ({ page }) => {
  const app = new SwagLabsApp(page);
  await app.login.goto();
  await app.login.login('standard_user', 'secret_sauce');
  await app.inventory.expectLoaded();
  await app.inventory.addProduct('Sauce Labs Backpack');
  await page.locator('[data-test="shopping-cart-link"]').click();
  await app.cart.checkout();
  await app.checkout.fillCustomer('Kaushal', 'Sharma', '201301');
  await app.checkout.finishOrder();
  await app.checkout.expectConfirmation();
});
