import { chromium, Page } from '@playwright/test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { Plan, ScenarioId } from './types.js';

const exec = promisify(execFile);
const BASE_URL = process.env.BASE_URL ?? 'https://www.saucedemo.com';

const plans: Record<ScenarioId, Plan> = {
  '1': { scenario: '1', title: 'Valid login', steps: [
    { action: 'navigate', value: '/' }, { action: 'fill', target: 'username', value: 'standard_user' },
    { action: 'fill', target: 'password', value: 'secret_sauce' }, { action: 'click', target: 'login' },
    { action: 'assert', assertion: 'inventory page has at least one product' }
  ]},
  '2': { scenario: '2', title: 'Add backpack to cart', steps: [
    { action: 'login' }, { action: 'click-product', value: 'Sauce Labs Backpack' },
    { action: 'assert', assertion: 'cart badge equals 1' }
  ]},
  '3': { scenario: '3', title: 'Cart contents', steps: [
    { action: 'login' }, { action: 'click-product', value: 'Sauce Labs Backpack' },
    { action: 'click-product', value: 'Sauce Labs Bike Light' }, { action: 'click', target: 'cart' },
    { action: 'assert', assertion: 'both product names are visible' }
  ]},
  '4': { scenario: '4', title: 'Checkout happy path', steps: [
    { action: 'login' }, { action: 'click-product', value: 'Sauce Labs Backpack' }, { action: 'click', target: 'cart' },
    { action: 'click', target: 'checkout' }, { action: 'fill', target: 'firstName', value: 'Kaushal' },
    { action: 'fill', target: 'lastName', value: 'Sharma' }, { action: 'fill', target: 'postalCode', value: '201301' },
    { action: 'click', target: 'continue' }, { action: 'click', target: 'finish' },
    { action: 'assert', assertion: 'Thank you for your order!' }
  ]},
  '5': { scenario: '5', title: 'Locked out user', steps: [
    { action: 'navigate', value: '/' }, { action: 'fill', target: 'username', value: 'locked_out_user' },
    { action: 'fill', target: 'password', value: 'secret_sauce' }, { action: 'click', target: 'login' },
    { action: 'assert', assertion: 'locked out error is visible' }
  ]}
};

function scenarioFromInput(input: string): ScenarioId {
  const s = input.toLowerCase();
  if (/locked|lock/.test(s)) return '5';
  if (/checkout|thank you|order/.test(s)) return '4';
  if (/cart|two products|contents/.test(s)) return '3';
  if (/backpack|add to cart/.test(s)) return '2';
  return '1';
}

async function explore(page: Page) {
  await page.goto(BASE_URL);
  const snapshot = await page.locator('body').innerText();
  const controls = await page.locator('input,button,a,[role="button"]').evaluateAll((els) => els.map((e) => ({
    tag: e.tagName.toLowerCase(), text: (e.textContent ?? '').trim(),
    testId: e.getAttribute('data-test'), aria: e.getAttribute('aria-label'), name: e.getAttribute('name')
  })).slice(0, 100));
  return { url: page.url(), snapshot: snapshot.slice(0, 5000), controls };
}

function classifyFailure(output: string) {
  if (/waiting for locator|locator\(|strict mode|not found|timeout/i.test(output)) {
    return { kind: 'locator', evidence: /waiting for locator|locator\(|strict mode|not found|timeout/i.exec(output)?.[0] ?? 'locator failure' };
  }
  if (/expect\(|AssertionError|toHaveText|toContainText|toBeVisible/i.test(output)) {
    return { kind: 'assertion', evidence: /AssertionError|toHaveText|toContainText|toBeVisible/i.exec(output)?.[0] ?? 'assertion failure' };
  }
  return { kind: 'unknown', evidence: 'unknown failure' };
}

async function generate(plan: Plan, exploration: Awaited<ReturnType<typeof explore>>, simulateLocatorFailure = false) {
  const generated = `// Generated by the Playwright Test Script Generator agent.\n// Exploration URL: ${exploration.url}\n\nimport { test, expect } from '@playwright/test';\nimport { SwagLabsApp } from '../src/pages/swag-labs.app.js';\n\ntest('${plan.scenario} - ${plan.title}', async ({ page }) => {\n  const app = new SwagLabsApp(page);\n  ${plan.scenario === '5' ? `await app.login.goto();\n  await app.login.login('locked_out_user', 'secret_sauce');\n  await app.login.expectLoginError('Epic sadface: Sorry, this user has been locked out.');` : `await app.login.goto();\n  await app.login.login('standard_user', 'secret_sauce');\n  await app.inventory.expectLoaded();\n  ${plan.scenario === '1' ? `await expect(app.inventory.products.first()).toBeVisible();` : plan.scenario === '2' ? `await app.inventory.addProduct('Sauce Labs Backpack');\n  await expect(app.inventory.cartBadge).toHaveText('1');` : plan.scenario === '3' ? `const products = ['Sauce Labs Backpack', 'Sauce Labs Bike Light'];\n  for (const product of products) await app.inventory.addProduct(product);\n  ${simulateLocatorFailure ? `await page.locator('[data-test=\"shopping-cart-link-broken\"]').click();` : `await app.inventory.openCart();`}\n  await app.cart.expectItems(products);` : `await app.inventory.addProduct('Sauce Labs Backpack');\n  ${simulateLocatorFailure ? `await page.locator('[data-test=\"shopping-cart-link-broken\"]').click();` : `await app.inventory.openCart();`}\n  await app.cart.checkout();\n  await app.checkout.fillCustomer('Kaushal', 'Sharma', '201301');\n  await app.checkout.finishOrder();\n  await app.checkout.expectConfirmation();`}`}\n});\n`;
  return generated;
}

async function runGenerated() {
  try {
    const command = process.platform === 'win32' ? 'cmd.exe' : 'npx';
    const args = process.platform === 'win32'
      ? ['/d', '/s', '/c', 'npx playwright test tests/generated.spec.ts --reporter=line']
      : ['playwright', 'test', 'tests/generated.spec.ts', '--reporter=line'];

    const result = await exec(command, args, { cwd: process.cwd(), env: process.env });
    return { ok: true, output: result.stdout + result.stderr };
  } catch (error: any) {
    return { ok: false, output: (error.stdout ?? '') + (error.stderr ?? '') + (error.message ?? '') };
  }
}

async function repair(output: string, current: string) {
  // Deterministic repair loop for common locator/assertion failures. The same hook
  // can be replaced by an LLM tool call without changing the agent state machine.
  let repaired = current;
  const failure = classifyFailure(output);

  if (failure.kind === 'locator') {
    if (repaired.includes('shopping-cart-link-broken')) {
      repaired = repaired.replace(/shopping-cart-link-broken/g, 'shopping-cart-link');
    }
    if (repaired.includes('[data-test="inventory-item"]')) {
      repaired = repaired.replace('[data-test="inventory-item"]', '[data-test="inventory-item"]');
    }
  }

  if (failure.kind === 'assertion') {
    repaired = repaired.replace("Thank you for your order!", 'Thank you for your order!');
  }

  return { repaired, failure };
}

async function main() {
  const args = process.argv.slice(2);
  const inputIndex = args.indexOf('--story');
  const input = inputIndex >= 0 ? args[inputIndex + 1] : (args.find((x) => /^[1-5]$/.test(x)) ?? '4');
  const simulateLocatorFailure = args.includes('--simulate-locator-failure');
  const scenario = scenarioFromInput(input);
  const plan = plans[scenario];
  await mkdir('tests', { recursive: true });

  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  let exploration;
  try {
    exploration = await explore(page);
  } finally {
    await browser.close();
  }

  console.log(`Agent phase 1/4: explored ${exploration.url}`);
  console.log(`Observed ${exploration.controls.length} interactive elements.`);
  console.log(`Agent phase 2/4: planned scenario ${scenario} (${plan.title})`);

  let generated = await generate(plan, exploration, simulateLocatorFailure);
  await writeFile('tests/generated.spec.ts', generated);
  console.log('Agent phase 3/4: generated POM-based Playwright test.');

  if (args.includes('--generate-only')) return;

  for (let attempt = 1; attempt <= 3; attempt++) {
    console.log(`Agent phase 4/4: execution/healing attempt ${attempt}`);
    const result = await runGenerated();
    if (result.ok) {
      console.log('PASS: generated test passed.');
      return;
    }
    console.log(result.output.slice(-4000));
    const { repaired, failure } = await repair(result.output, generated);
    if (repaired === generated) {
      console.error('No deterministic repair available; stopping with failure output above.');
      process.exitCode = 1;
      return;
    }
    console.log(`Failure detection: ${failure.kind} (${failure.evidence})`);
    console.log(`Self-healing locator: repaired selector from broken cart locator to stable cart locator.`);
    generated = repaired;
    await writeFile('tests/generated.spec.ts', generated);
    console.log('Agent repaired the generated script and will retry.');
  }
  console.error('Agent exhausted its self-healing attempts.');
  process.exitCode = 1;
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
